
skillMetadata:
  sections:
    - name: Deezer
      fields:
        - name: music_dir
          type: text
          label: Where to save downloaded Songs to
          value: "/opt/mycroft/music"
          placeholder: Path to music folder (must have mycroft Permissions)
        - name: arl
          type: text
          label: You can get the your arl by manually logging into Deezer using your browser and check the cookies and look for the value of arl.
          value: ""
          placeholder: Your deezer arl
